version: '2.4'
services:
  MixerDB:
    container_name: MixerDB
    image: siewer/mixingsecurity:mixer-db
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_DB=mixer
      - POSTGRES_USER=mixeruser
      - POSTGRES_PASSWORD=mixerpassword
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mixeruser -d mixer"]
      interval: 10s
      timeout: 5s
      retries: 1
  MixerVault:
    image: siewer/mixingsecurity:mixer-vault
    container_name: MixerVault
    ports:
      - 8200:8200
    environment:
      - WAIT_HOSTS=MixerDB:5432
      - VAULT_API_ADDR=http://127.0.0.1:8200
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API=http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    command: sh -c 'source /opt/mixer/start && source /opt/mixer/unseal'
    depends_on:
      MixerDB:
        condition: service_healthy
volumes:
  pgdata:
